### ISSUE TITLE
Get variables LESS_TERMCAP_* from lesskey file

### ISSUE THREAD

**Issue by olibre** [rivy/less#1]
The command `less` skips the variables `LESS_TERMCAP_*` defined in the `lesskey` file (e.g. `~/.less`).

This is because, the function `main()` retrieves the variables `LESS_TERMCAP_*`
before loading of the `lesskey` file. I propose to just invert two lines.

I explain that in details on this site:
https://unix.stackexchange.com/a/377221/13999

This is the current source code at line 110 in `main.c`

```c
/*
 * Process command line arguments and LESS environment arguments.
 * Command line arguments override environment arguments.
 */
is_tty = isatty(1);
get_term();
init_cmds();
init_charset();
init_line();
```

This is the fix I have validated on my computer:

```c
/*
 * Process command line arguments and LESS environment arguments.
 * Command line arguments override environment arguments.
 */
is_tty = isatty(1);
init_cmds();         /* Load lesskey file before */
get_term();          /* getting variables LESS_TERMCAP_* */
init_charset();
init_line();
```

I have just inverted two lines: `get_term();` and `init_cmds();`

Questions:

* Do you want a pull request ?
* Do you want to follow bug-fixes from upstream project ?

For information I have sent the same bug report a fix proposal to the `less` mainteners.

**Comment by rivy** [comment]
👍 

I, personally, use conditional commands in my ".profile" to customize the "LESS_TERMCAP_*" variables for various TERMs and OS variants.

But, given "lesskey"'s current coverage of other environment variables, this seems to me like a reasonable expansion of scope. If you'd like to create a PR, I'll merge it.

I'm not sure of your reception upstream.

I've tried contacting them about some of the modifications that I've done here (back in March), but received no responses. And Thomas Dickey's tone seems unsupportive on SO.

Notably, the one conversation that I saw about the "LESS_TERMCAP_*" variables was that they were for **debugging** and not to depend on them (see http://archive.is/S55UZ#77%). But since they've been around for many years and it's the only convenient way to set custom colors for the program under *nix, I, and obviously some others, use them liberally. (There was a suggestion to [use a custom TERM instead](https://unix.stackexchange.com/questions/108699/documentation-on-less-termcap-variables/356565#356565), but that seems somewhat ridiculous to expect from more casual users. And it changes the color scheme for *all* programs, not just `less`.)

**Comment by olibre** [comment]
All right, I have pull requested 😄  --> https://github.com/rivy/less/pull/2
Thank you for the explanations.

**Comment by rivy** [comment]
Got it.

I want to look at it a bit to "grok" the code it impacts. I might suggest a couple of small changes.

**Comment by rivy** [comment]
Fixed elsewhere... (in v530? per Nudelman).
